sudo: required
language: python
before_script:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" images.sbgenomics.com
  - docker ps -a
  - pip install pyyaml
script:
  - pwd
  - ls -ltra
  - python runtests.py ~/home/travis/build/markosbg/bunnyCI/ ./rabix.sh
services:
  - docker
