sudo: required
language: python

before_install:
  - docker pull carlad/sinatra

before_script:
  - pip install pyyaml
script:
  - cd examples
  - python runtests.py . ../rabix.sh
services:
  - docker
